---
# Sikker ansatt versjon kode
sikker-ansatt-version: v0.0.2

mde_onboarding_url: https://sslinux.blob.core.windows.net/salinux/cupheads-onboarding.py

# The tenant domain should be set to the domain part of the UPN of the users in the tenant
tenant_domain: example.no

# Set to object id of Entra ID groups as a comma seperated list
local_admin_groups: 11b794e0-b07c-4c80-a11c-ed9b825a48fe,46a87237-1e94-4011-864f-a2ef425d8f3c
