---
- name: Install and onboard Microsoft Defender for Endpoint
  hosts: localhost

  pre_tasks:
    - name: Load policy variables
      ansible.builtin.import_tasks:
        file: tasks/load-vars.yaml

  tasks:
    - name: Install and onboard Microsoft Defender for Endpoint
      ansible.builtin.import_tasks:
        file: tasks/install-defender.yaml
