---
- name: Enrole host using himmelblau
  hosts: localhost
  vars_files:
    - settings.yaml

  tasks:
    - name: Include customer spesific variables
      ansible.builtin.include_vars:
        file: "{{ customer_settings_file }}"

    - name: Install himmelblau agent
      ansible.builtin.import_tasks:
        file: tasks/install-himmelblau.yaml
