---
- name: Enrole host using himmelblau
  hosts: localhost

  pre_tasks:
    - name: Load policy variables
      ansible.builtin.import_tasks:
        file: tasks/load-vars.yaml

  tasks:
    - name: Print enrolement method
      ansible.builtin.debug:
        msg: "Enrolement method: {{ enrolement_method }}"

    - name: Enrole with himmelblau
      ansible.builtin.include_tasks:
        file: tasks/enrole-himmelblau.yaml
      when: enrolement_method == "himmelblau"

    - name: Enrole with Microsoft Intune
      ansible.builtin.include_tasks:
        file: tasks/enrole-intune.yaml
      when: enrolement_method == "intune"

    - name: Enrol using minimal method
      ansible.builtin.include_tasks:
        file: tasks/install-defender.yaml
      when: enrolement_method == "minimal"
