---
- name: Enrole host using himmelblau
  hosts: localhost

  pre_tasks:
    - name: Load policy variables
      ansible.builtin.import_tasks:
        file: tasks/load-vars.yaml

  tasks:
    - name: Install himmelblau agent
      ansible.builtin.import_tasks:
        file: tasks/install-himmelblau.yaml
