---
- name: Install and onboard Microsoft Defender for Endpoint
  hosts: localhost
  vars_files:
    - settings.yaml

  tasks:
    - name: Include customer spesific variables
      ansible.builtin.include_vars:
        file: "{{ playbook_dir }}/../customer-settings.yaml"

    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /tmp/mde_install
        state: directory
        mode: '0755'

    - name: Download Onboarding script
      ansible.builtin.get_url:
        url: "{{ mde_installer_url }}"
        dest: /tmp/mde_install/mde_installer.sh
        mode: '0500'

    - name: Download Onboarding json
      ansible.builtin.get_url:
        url: "{{ mde_onboarding_url }}"
        dest: /tmp/mde_install/mdatp_onboard.json
        mode: '0600'

    - name: Install MDE on host
      ansible.builtin.script:
        cmd: "/tmp/mde_install/mde_installer.sh --install --channel prod --onboard /tmp/mde_install/mdatp_onboard.json --verbose --log-path {{ mde_installer_log }}"
