---
- name: Configure Microsoft Edge policies
  hosts: localhost

  tasks:
    - name: Create Edge policy directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
        owner: root
        group: root
      loop:
        - /etc/opt/edge/policies/managed
        - /etc/opt/edge/policies/recommended

    - name: Create managed Edge policy file
      ansible.builtin.template:
        src: managed-edge_policy.j2
        dest: /etc/opt/edge/policies/managed/upheads-edge-policy.json
        owner: root
        group: root
        mode: '0644'

    - name: Create recommended Edge policy file
      ansible.builtin.template:
        src: recommended_edge-policy.j2
        dest: /etc/opt/edge/policies/recommended/upheads-edge-policy.json
        owner: root
        group: root
        mode: '0644'
