---
- name: Configure Microsoft Edge policies
  hosts: localhost
  vars_files:
    - settings.yaml

  tasks:
    - ansible.builtin.include_vars:
        file: "{{ playbook_dir }}/../customer-settings.yaml"

    - name: Merge default and customer managed Edge policies
      ansible.builtin.set_fact:
        edge_managed_policies: "{{ edge_managed_policies + edge_managed_policies_customer | default([]) }}"

    - name: Create Edge policy directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
        owner: root
        group: root
      loop:
        - /etc/opt/edge/policies/managed
        - /etc/opt/edge/policies/recommended

    - name: Create managed Edge policy file
      ansible.builtin.template:
        src: managed-edge_policy.j2
        dest: /etc/opt/edge/policies/managed/upheads-edge-policy.json
        owner: root
        group: root
        mode: '0644'
      loop: "{{ edge_managed_policies }}"

    - name: Create recommended Edge policy file
      ansible.builtin.template:
        src: recommended_edge-policy.j2
        dest: /etc/opt/edge/policies/recommended/upheads-edge-policy.json
        owner: root
        group: root
        mode: '0644'
      loop: "{{ edge_recommended_policies }}"
