#!/bin/bash

policyDir="/usr/local/src/sikker-ansatt/policies"
policyFile="${1%.*}"
policyLogFile="/var/log/sa-policy-${policyFile}.log"

shift 1

exec >> "${policyLogFile}" 2>&1

echo "Running Intune policy: ${policyFile} at $(date -Iseconds)" > "${policyLogFile}"

if [ -f /usr/local/src/sikker-ansatt/venv/bin/activate ]; then
    source /usr/local/src/sikker-ansatt/venv/bin/activate
else
    echo "Virtual environment not found!" >> "${policyLogFile}"
    exit 250
fi

# Load all customer variables and export them all for Ansible to read
set -o allexport
source "/usr/local/src/sikker-ansatt/customer-settings.env"
set +o allexport

if [ -f /usr/local/src/sikker-ansatt/venv/bin/ansible-playbook ]; then
    /usr/local/src/sikker-ansatt/venv/bin/ansible-playbook "${policyDir}/${policyFile}.yaml" "${@}" >> "${policyLogFile}"
else
    echo "Cant find ansible installation" >> "${policyLogFile}"
    exit 251
fi

echo "Finished Intune policy: ${policyFile} at $(date -Iseconds)" >> "${policyLogFile}"
