#!/bin/sh

policyDir="/usr/local/src/sikker-ansatt/policies"
policyFile="${1%.*}"
policyLogFile="/var/log/sa-policy-${policyFile}.log"

exec >> "${policyLogFile}" 2>&1

echo "Running Intune policy: ${policyFile} at $(date -Iseconds)" >> "${policyLogFile}"

if [ -f /usr/local/src/sikker-ansatt/venv/bin/activate ]; then
 . /usr/local/src/sikker-ansatt/venv/bin/activate
else
 echo "Virtual environment not found!" >> "${policyLogFile}"
 exit 250
fi

ansible-playbook "${policyDir}/${policyFile}.yaml" >> "${policyLogFile}"

echo "Finished Intune policy: ${policyFile} at $(date -Iseconds)" >> "${policyLogFile}"
