---
# Basic settings
customer_settings_file: "/usr/local/src/sikker-ansatt/customer-settings.env"
file_header_slash_block: "// Managed by Sikker Ansatt - support@upheads.no"

# Defender settings
mde_installer_log: "/var/log/sa-mde-installer.log"
mde_installer_url: "https://raw.githubusercontent.com/microsoft/mdatp-xplat/refs/heads/master/linux/installation/mde_installer.sh"
mde_onboarding_url: "https://sikkeransatt.blob.core.windows.net/no00000/mdatp_onboard.json"

# MSEdge configuration
edge_managed_policies:
  - key: BrowserSignin
    value: 1
  - key: ForceSync
    value: true
  - key: NonRemovableProfileEnabled
    value: true
  - key: PasswordManagerEnabled
    value: false
  - key: ManagedAccountsSigninRestriction
    value: "primary_account_strict"
  - key: RestrictSigninToPattern
    value: "*@{{ tenant_domain }}"
edge_recommended_policies:
  - key: HubsSidebarEnabled
    value: false

# Onedrive
curl_version_required: "8.14.1"

# Update ring
unattended_upgrades_config:
  - 'APT::Periodic::Update-Package-Lists "1"'
  - 'APT::Periodic::Download-Upgradeable-Packages "0"'
  - 'APT::Periodic::AutocleanInterval "0"'
  - 'APT::Periodic::Unattended-Upgrade "1"'
unattended_upgrades_settings:
  - 'Unattended-Upgrade::Automatic-Reboot "false"'
