---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true

- name: Remove Microsoft Intune package
  ansible.builtin.apt:
    name: intune-portal
    state: absent

- name: Install dependencies
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gpg

- name: Add Himmelblau repo using key from URL
  ansible.builtin.deb822_repository:
    name: himmelblau
    types: deb
    uris: "https://packages.himmelblau-idm.org/stable/latest/deb/ubuntu24.04/"
    suites: "./"
    signed_by: https://packages.himmelblau-idm.org/himmelblau.asc
    state: present
    enabled: true
    architectures: amd64

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true

- name: Install himmelblau
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - himmelblau
    - pam-himmelblau
    - nss-himmelblau
    - himmelblau-qr-greeter
    - himmelblau-sso
    - o365
- name: Ensure /etc/himmelblau exists
  ansible.builtin.file:
    path: /etc/himmelblau
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Create /etc/himmelblau/himmelblau.conf from template
  ansible.builtin.template:
    src: himmelblau.conf.j2
    dest: /etc/himmelblau/himmelblau.conf
    owner: root
    group: root
    mode: "0644"

- name: Ensure himmelblau service is enabled and started
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - himmelblaud
    - himmelblaud-tasks
